spring.application.name=desafio-final-rpg

spring.datasource.url=jdbc:postgresql://localhost:5433/simulador
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true